version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    restart: unless-stopped
    ports:
      - '8123:8080'
    volumes:
      - $DOCKERDIR/stirling/trainingData:/usr/share/tessdata #Required for extra OCR languages
      - $DOCKERDIR/stirling/extraConfigs:/configs
      - $DOCKERDIR/stirling/customFiles:/customFiles/
      - $DOCKERDIR/stirling/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=$LANGS

